spring:
  redis:
    ssl: false
    host: redis # Use the service name defined in docker-compose.yml
    port: 6379
    database: 0
    timeout: 1000
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        min-idle: 0
        max-idle: 20

server:
  port: 8082

